-- сервисный пользователь Airflow
CREATE USER airflow WITH PASSWORD 'airflow';

-- учебный админ БД
CREATE USER admin WITH PASSWORD 'admin';

ALTER DATABASE airflow OWNER TO airflow;

GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO admin;

\c airflow;

GRANT ALL ON SCHEMA public TO airflow;
GRANT ALL ON SCHEMA public TO admin;

GRANT ALL ON ALL TABLES IN SCHEMA public TO airflow;
GRANT ALL ON ALL TABLES IN SCHEMA public TO admin;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO airflow;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO airflow;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO admin;